### ISSUE TITLE
Conflicting package versions in requirements.txt

### ISSUE THREAD

**Issue by sumitsoman** [netop-team/Telco-RAG#1]
The current requirements.txt has multiple versions of GitPython which gives the following error:

    ERROR: Cannot install GitPython==3.1.37 and GitPython==3.1.43 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested GitPython==3.1.37
    The user requested GitPython==3.1.43

**Comment by netop-team** [comment]
This conflict has been resolved in the repo.

**Comment by chemeris** [comment]
The issue is still in the repo, see: https://github.com/netop-team/Telco-RAG/blob/main/Telco-RAG_api/requirements.txt

The fix has probably not been pushed
